name: "2.3] Workflow déclenché seulement pour une branche"
on:
  push:
    branches:
      - demo

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello, world !"
