name: "3.2] Workflow réguulier"
on:
  schedule:
    - cron: "0/10 * * * *"
    - cron: "0 0 1 * *"
jobs:
  say_hello:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run: |
          echo "Hello, world!".
  
