name: "4.2] Definition des secrets"

on:
  push:

jobs:
  confidential_data:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
    steps:
      - name: "Confidential data"
        run: |
          echo "La valeur de SUPER_SECRET est $SUPER_SECRET"
