name: "5.1] Message d'informations

on:
  push:
jobs:
  information_display:
    runs-on: ubuntu-latest
    steps:
      - name: "Notice"
        run: |
          echo "::notice::Ceci est une notice."
      - name: "Warning"
        run: |
          echo "::warning::Ceci est un avertissement."
      - name: "error"
        run: |
          echo "::error::Une erreur est survenue."
